2022-03-01 19:40:02,988 INFO    MainThread:1751 [wandb_setup.py:_flush():75] Loading settings from /opt/ml/.config/wandb/settings
2022-03-01 19:40:02,988 INFO    MainThread:1751 [wandb_setup.py:_flush():75] Loading settings from /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/settings
2022-03-01 19:40:02,988 INFO    MainThread:1751 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-01 19:40:02,988 INFO    MainThread:1751 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2022-03-01 19:40:02,988 INFO    MainThread:1751 [wandb_init.py:_log_setup():386] Logging user logs to /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/run-20220301_194002-22utc8hj/logs/debug.log
2022-03-01 19:40:02,988 INFO    MainThread:1751 [wandb_init.py:_log_setup():387] Logging internal logs to /opt/ml/code/git_bcnlp/special_mission/hyunah/wandb/run-20220301_194002-22utc8hj/logs/debug-internal.log
2022-03-01 19:40:02,988 INFO    MainThread:1751 [wandb_init.py:_jupyter_setup():336] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x7f9ee30bfdf0>
2022-03-01 19:40:02,989 INFO    MainThread:1751 [wandb_init.py:init():420] calling init triggers
2022-03-01 19:40:02,989 INFO    MainThread:1751 [wandb_init.py:init():425] wandb.init called with sweep_config: {}
config: {}
2022-03-01 19:40:02,989 INFO    MainThread:1751 [wandb_init.py:init():471] starting backend
2022-03-01 19:40:02,989 INFO    MainThread:1751 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-01 19:40:03,003 INFO    MainThread:1751 [backend.py:ensure_launched():219] starting backend process...
2022-03-01 19:40:03,018 INFO    MainThread:1751 [backend.py:ensure_launched():224] started backend process with pid: 1790
2022-03-01 19:40:03,019 INFO    MainThread:1751 [wandb_init.py:init():480] backend started and connected
2022-03-01 19:40:03,037 INFO    MainThread:1751 [wandb_run.py:_label_probe_notebook():921] probe notebook
2022-03-01 19:40:03,038 INFO    MainThread:1751 [wandb_run.py:_label_probe_notebook():931] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2022-03-01 19:40:03,038 INFO    MainThread:1751 [wandb_init.py:init():550] updated telemetry
2022-03-01 19:40:03,062 INFO    MainThread:1751 [wandb_init.py:init():581] communicating current version
2022-03-01 19:40:03,866 INFO    MainThread:1751 [wandb_init.py:init():586] got version response 
2022-03-01 19:40:03,867 INFO    MainThread:1751 [wandb_init.py:init():596] communicating run to backend with 30 second timeout
2022-03-01 19:40:04,082 INFO    MainThread:1751 [wandb_init.py:init():624] starting run threads in backend
2022-03-01 19:40:07,021 INFO    MainThread:1751 [wandb_run.py:_console_start():1827] atexit reg
2022-03-01 19:40:07,022 INFO    MainThread:1751 [wandb_run.py:_redirect():1701] redirect: SettingsConsole.WRAP
2022-03-01 19:40:07,022 INFO    MainThread:1751 [wandb_run.py:_redirect():1738] Wrapping output streams.
2022-03-01 19:40:07,023 INFO    MainThread:1751 [wandb_run.py:_redirect():1762] Redirects installed.
2022-03-01 19:40:07,023 INFO    MainThread:1751 [wandb_init.py:init():651] run started, returning control to user process
2022-03-01 19:40:07,026 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:07,026 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:07,031 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:07,032 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:07,032 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:07,036 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:07,038 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:07,038 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:07,042 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:07,044 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:07,044 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:07,049 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:10,469 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:10,470 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:10,474 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:10,475 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:10,475 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:10,479 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:10,480 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:10,480 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:10,484 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:10,485 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:10,485 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:10,489 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:10,689 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:10,690 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:40:56,219 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:40:56,220 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:40:56,221 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:41:00,783 INFO    MainThread:1751 [wandb_init.py:_resume_backend():308] resuming backend
2022-03-01 19:45:58,661 INFO    MainThread:1751 [wandb_init.py:_pause_backend():299] pausing backend
2022-03-01 19:45:58,661 INFO    MainThread:1751 [jupyter.py:save_ipynb():374] not saving jupyter notebook
2022-03-01 19:48:33,800 INFO    MainThread:1751 [wandb_run.py:_atexit_cleanup():1797] got exitcode: 0
2022-03-01 19:48:33,801 INFO    MainThread:1751 [wandb_run.py:_restore():1769] restore
2022-03-01 19:48:34,721 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 879
  total_bytes: 879
}

2022-03-01 19:48:34,947 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 1
}
pusher_stats {
  uploaded_bytes: 879
  total_bytes: 879
}

2022-03-01 19:48:35,264 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 4
}
pusher_stats {
  uploaded_bytes: 879
  total_bytes: 4143
}

2022-03-01 19:48:35,367 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 879
  total_bytes: 4469
}

2022-03-01 19:48:35,470 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 879
  total_bytes: 4469
}

2022-03-01 19:48:35,572 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4469
  total_bytes: 4469
}

2022-03-01 19:48:35,674 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4469
  total_bytes: 4469
}

2022-03-01 19:48:35,776 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4469
  total_bytes: 4469
}

2022-03-01 19:48:35,878 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4469
  total_bytes: 4469
}

2022-03-01 19:48:35,980 INFO    MainThread:1751 [wandb_run.py:_wait_for_finish():1929] got exit ret: file_counts {
  wandb_count: 5
}
pusher_stats {
  uploaded_bytes: 4469
  total_bytes: 4469
}

